//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLQuanCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int TableID { get; set; }
        public string TableName { get; set; }
        public int Status { get; set; }
    }
}
